workflow update

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -1,4 +1,5 @@
 name: CI
+
 on:
   push:
     branches: [ "main" ]
@@ -12,19 +13,31 @@ permissions:
 jobs:
   build:
     runs-on: ubuntu-latest
+    container:
+      options: --user root
     steps:
       - uses: actions/checkout@v3
-      - name: install packages
-        run: make install
-      - name: lint
-        run: make lint
-      - name: run model
-        run: make ml_run
+      - name : install packages
+        run : make install
       - name: test
         run: make test
-      - name: format
-        run: make format
-      - name: generate_and_push
-        run: make generate_and_push
-      - name: deploy
-        run: make deploy
+      - name : format
+        run : make format
+      - name: lint
+        run: make lint
+      - name: Archive and Upload Artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: ml_pipeline-artifacts
+          path: ${{ github.workspace }}
+        
+      - name: Save to repository
+        env:
+          GH_TOKEN: ${{ secrets.GH_TOKEN }}
+        run: |
+          echo GH_TOKEN: "${GH_TOKEN}"
+          git config --global user.name 'github-actions'
+          git config --local user.email "action@github.com"
+          git add .
+          git commit -m "Added Results" || echo "ignore commit failure, proceed"
+          git push
